title: Irina-Maria Ionita
url: "https://irinaionita.eu"
description: "Hello I'm Irina - a researcher working at the intersection of human rights, EU policy, and anti-trafficking work."
og_image: "https://irinaionita.eu/assets/images/irina-eu-flag.png"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: # "https://github.com/irmaio"
footer_text: # "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "assets/documents/CV_Ionita Irina (short).pdf"
 - name: "Contact"
   link: "contact"
